### ISSUE TITLE
What are you building the docker container on?

### ISSUE THREAD

**Issue by Digital-Daz** [RocketChat/Rocket.Chat.Embedded.arm64#2]
On ubuntu 20.04 arm64 on the Rapberry Pi4 I am getting:

---> Running in 130407ba45b5
+ cd /app/bundle/programs/server
+ npm install
Aborted (core dumped)

**Comment by Sing-Li** [comment]
@PBXForums  Hmm.  

Yes.  I've encountered multiple problem on Pi 4 + Ubuntu 20.04 before.   Suggest you use 18.04LTS 64bit on same.  

One of the problem was https://github.com/RocketChat/Rocket.Chat.Embedded.arm64/issues/1

ALSO - I've had great luck with the latest Raspbian 64bit that recently beta'd with the 8GB RAM Pi 4 release.

**Comment by Sing-Li** [comment]
For faster response please join our 24 x 7 Pi channel.    https://open.rocket.chat/channel/raspberrypi
